# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 15:52
from __future__ import unicode_literals

from django.db import migrations, models


def migrate_links(apps, schema_editor):
    Stream = apps.get_model("stream", "Stream")
    for stream in Stream.objects.all():
        data = map(lambda s: s.url, stream.links.all())
        stream.youtube_links = "\n".join(data)
        stream.save()

class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='youtube_links',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_links, hints={"target_db": "default"})
    ]
