# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_stream_youtube_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='links',
        ),
        migrations.DeleteModel(
            name='StreamLink',
        ),
    ]
