# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_auto_20160719_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='play_random',
            field=models.BooleanField(default=False),
        ),
    ]
