# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0004_stream_play_random'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('keywords', models.CharField(max_length=255, verbose_name="\u0420\u0430\u0437\u0434\u0435\u043b\u0438\u0442\u0435\u043b\u044c ','")),
                ('channels', models.CharField(max_length=512)),
                ('update_frequency', models.PositiveSmallIntegerField()),
                ('video_length', models.PositiveSmallIntegerField()),
                ('slug', models.SlugField(unique=True)),
                ('img', models.ImageField(upload_to='streams')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
