# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0005_autostream'),
    ]

    operations = [
        migrations.AddField(
            model_name='autostream',
            name='name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autostream',
            name='keywords',
            field=models.CharField(max_length=255),
        ),
    ]
