# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0006_auto_20160818_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('icon', models.ImageField(upload_to='icons')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='autostream',
            name='channels',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='autostream',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='autostream',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stream.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stream',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stream.Category'),
            preserve_default=False,
        ),
    ]
