# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0008_category_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='autostream',
            name='description',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stream',
            name='description',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
