# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0009_auto_20160905_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('background', models.ImageField(upload_to='backgrounds')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='background',
        ),
        migrations.AddField(
            model_name='category',
            name='backgrounds',
            field=models.ManyToManyField(to='stream.CategoryBackground'),
        ),
    ]
