# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0010_auto_20160905_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='mask',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
