# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0012_autostream_is_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='channels',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='stream',
            name='is_news',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stream',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stream',
            name='update_frequency',
            field=models.PositiveSmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stream',
            name='video_length',
            field=models.PositiveSmallIntegerField(default=None),
            preserve_default=False,
        ),
    ]
