# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-05 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0012_autostream_is_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.TextField(),
        ),
    ]
