# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0013_auto_20161005_1149'),
        ('stream', '0013_auto_20161011_0825'),
    ]

    operations = [
    ]
