# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 02:27
from __future__ import unicode_literals

from django.db import migrations


def migrate_autostreams(apps, schema_editor):
    AutoStream = apps.get_model('stream', 'AutoStream')
    Stream = apps.get_model('stream', 'Stream')
    for a in AutoStream.objects.all():
        Stream.objects.create(
            name=a.name,
            description=a.description,
            keywords=a.keywords,
            channels=a.channels,
            update_frequency=a.update_frequency,
            video_length=a.video_length,
            slug=a.slug,
            img=a.img,
            category=a.category,
            is_news=a.is_news
        )



class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0014_merge'),
    ]

    operations = [
        migrations.RunPython(migrate_autostreams, hints={'target_db':
                                                         'default'})
    ]
