# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0015_auto_20161011_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autostream',
            name='category',
        ),
        migrations.AlterField(
            model_name='stream',
            name='youtube_links',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='AutoStream',
        ),
    ]
