# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0016_auto_20161012_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
