# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-25 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0017_stream_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='plex_playlist_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
