# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-29 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0018_stream_plex_playlist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='hls_root_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stream',
            name='plex_playlist_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stream',
            name='update_frequency',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='video_length',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
